# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudslash < Formula
  desc "CloudSlash - Infrastructure Optimization Tool"
  homepage "https://github.com/DrSkyle/cloudslash"
  version "2.2.6"

  on_macos do
    on_intel do
      url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Darwin_x86_64.tar.gz"
      sha256 "436a78c4e26c10ccaba95ac865ba8017632c1b7dee64d6a18fd9583e2dd7ffce"

      def install
        bin.install "cloudslash"
      end
    end
    on_arm do
      url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Darwin_arm64.tar.gz"
      sha256 "345deafd4f06435694bcba0c7a008204edd65a3399021ea8e73f0f64f425273d"

      def install
        bin.install "cloudslash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Linux_x86_64.tar.gz"
        sha256 "2d8fdc777128c8eb9ff399886c7d7e7a5c8e0d71b6362be58168eb15b50a9abc"

        def install
          bin.install "cloudslash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Linux_arm64.tar.gz"
        sha256 "0c57dd19c69fd9fd2ba82a06318da776f9b40689f592e4a386349fde6c64aaf6"

        def install
          bin.install "cloudslash"
        end
      end
    end
  end

  test do
    system "#{bin}/cloudslash --version"
  end
end
