# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudslash < Formula
  desc "CloudSlash - Infrastructure Optimization Tool"
  homepage "https://github.com/DrSkyle/cloudslash"
  version "2.2.6"

  on_macos do
    on_intel do
      url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Darwin_x86_64.tar.gz"
      sha256 "82b3345478fa5018713ac51299febe7da9ea5efcdaf59b1d6e7a84672d85a2cd"

      def install
        bin.install "cloudslash"
      end
    end
    on_arm do
      url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Darwin_arm64.tar.gz"
      sha256 "825ecfb47744129b80ed0cb5d58d5ef52d8efcef8846166651cd79d6dd9322f1"

      def install
        bin.install "cloudslash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Linux_x86_64.tar.gz"
        sha256 "aebc2e501e99ed75848e07e45f4c6b3417d22014f48cc0fa84a9896bf4923fcf"

        def install
          bin.install "cloudslash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Linux_arm64.tar.gz"
        sha256 "d717cb50e4ce7aef78d73cdc143b636e77d6b5172207087296ad681451ed07ce"

        def install
          bin.install "cloudslash"
        end
      end
    end
  end

  test do
    system "#{bin}/cloudslash --version"
  end
end
