# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudslash < Formula
  desc "CloudSlash - Infrastructure Optimization Tool"
  homepage "https://github.com/DrSkyle/cloudslash"
  version "2.2.6"

  on_macos do
    on_intel do
      url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Darwin_x86_64.tar.gz"
      sha256 "7ea04dead6c2a05f30f7f0bbed94a1282ef4770b80c84a7ae9d5e48c0af82661"

      def install
        bin.install "cloudslash"
      end
    end
    on_arm do
      url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Darwin_arm64.tar.gz"
      sha256 "b48160ec3233fedf5fd7615ba3b2be1987bd451518432adbd4a35ef792cfbe9b"

      def install
        bin.install "cloudslash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Linux_x86_64.tar.gz"
        sha256 "b00dac769f010ce38101a9983f9899a1ba4d51a2150bcaf348299c28534ee7cf"

        def install
          bin.install "cloudslash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DrSkyle/CloudSlash/releases/download/v2.2.6/cloudslash_Linux_arm64.tar.gz"
        sha256 "05382b7862875921d88eaccc92dfa3d1d8c7b9c8a035c106b99583a6239d8381"

        def install
          bin.install "cloudslash"
        end
      end
    end
  end

  test do
    system "#{bin}/cloudslash --version"
  end
end
